version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.10.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=khoi
      - RABBITMQ_DEFAULT_PASS=khoideptrai
    ports:
      - '5672:5672'
      - '15672:15672'